version: "3"

networks:
    local:

services:
    wraith:
        image: romplabs/wraith
        build:
            context: .
        restart: always
        environment:
            - DISCORD_TOKEN=
            - MONGO_URL=
            - MONGO_USER=
            - MONGO_PASS=
            - MONGO_DATA=
        networks:
            - local
