version: '3'

networks:
    local:

volumes:
    database_storage:

services:
    wraith:
        image: romplabs/wraith
        build:
            context: .
        restart: always
        environment: 
            - DISCORD_TOKEN=DISCORD-TOKEN
            - MYSQL_ADDR=127.0.0.1
            - MYSQL_USER=admin
            - MYSQL_PASS=password
            - MYSQL_DATA=wraith
        networks:
            - local

    database:
        image: mysql
        restart: unless-stopped
        expose:
            - 3306
        environment: 
            - MYSQL_ROOT_PASSWORD=wraith
            - MYSQL_USER=wraith
            - MYSQL_PASSWORD=wraith
            - MYSQL_DATABASE=wraith
        volumes: 
            - database_storage
        networks:
            - local
